# Generated by Django 4.0 on 2022-06-17 22:10

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=product.models.nameFile)),
                ('title', models.CharField(max_length=128)),
                ('size', models.CharField(blank=True, max_length=56, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=56, verbose_name='Phone number')),
                ('address', models.TextField()),
                ('summa', models.CharField(max_length=128)),
                ('products', models.ManyToManyField(related_name='pruducts', to='product.Product')),
            ],
            options={
                'verbose_name': 'Orders',
                'verbose_name_plural': 'Order',
                'db_table': 'order',
            },
        ),
    ]
