# Generated by Django 4.0 on 2022-04-30 07:52

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=56, null=True)),
                ('image', models.ImageField(upload_to=blog.models.nameFile)),
                ('title', models.CharField(max_length=128)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('desctiption', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
