# Generated by Django 4.0 on 2022-06-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_orderitem_items_orderitem_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sum_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
